version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/"
      - "/examples/api"
      - "/examples/observe"
    schedule:
      interval: weekly
    groups:
      python-dev:
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
