guardrails:
  - guardrail_name: apparitor
    litellm_params:
      guardrail: examples.litellm.apparitor_guardrail.ApparitorGuardrail
      mode:
        - pre_call
        - post_call
      default_on: true
